name: Netch Release CI
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Build
      shell: pwsh
      run: |
        .\build.ps1 -Configuration Release -OutputPath release
    - name: Package
      shell: pwsh
      run: |
        7z a -mx9 Netch-LTS.7z release
        7z rn Netch-LTS.7z release Netch
        echo "NETCH_SHA256=$(.\sha256.ps1 Netch-LTS.7z)" | Out-File -Append -Encoding UTF8 -FilePath $Env:GITHUB_ENV
    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        prerelease: ${{ contains(github.ref, 'Beta') }}
        draft: false
        files: |
          Netch-LTS.7z
        body: |
          #### Netch
          [![](https://img.shields.io/badge/Telegram-Channel-blue)](https://t.me/netch_channel) [![](https://img.shields.io/badge/Telegram-Group-green)](https://t.me/netch_group)
          ## Netch-LTS
          ### 更新日志
          * 这是 GitHub Actions 自动化部署，更新日志应该很快会手动更新
          ### 校验和
          | 文件名 | SHA256 |
          | :- | :- |
          | Netch-LTS.7z | ${{ env.Netch_SHA256 }} |
